### ISSUE TITLE
lin-cms-vvlog Roadmap

### ISSUE THREAD

**Issue by luoyunchong** [luoyunchong/lin-cms-vvlog#7]
## MILESTONE: MID 

- [x]  代码风格配置
- [x] GitHub Actions 自动化部署
- [x] 日志记录（审计日志-错误日志)
- [x]  用户关闭评论时，无法对随笔进行评论
- [x] 评论随笔(内容支持超链接)
- [ ] 评论随笔(内容支持emoji)
- [x] 首页增加开源地址介绍
- [x] 文章详情页：文章的标题显示在浏览器上的title 上。
- [x] 文章详情页，图片太大时，预览效果差，无法正常查看。
## 文档

- [ ]  完善前后端设计的相关文档说明

## Bug
- [x] 查看别人关注的标签时，这些标签当前登录人未关注，却显示已关注。
- [x] 账号不存在时，如删除了用户，但文章还在，目前显示该用户已注销，但无法取消关注此人。
- [x] QQ登录的BUG
- [x]  移动端登录后样式错乱
- [x]  我的消息，在移动端下表现太差。兼容移动设备。保持可用性。
- [x]  手机个人主页不兼容。关注，粉丝的个性签名建议不显示
- [x] 标签管理，列表上有些没有图片，在第二页后，编辑后，页数显示不正确。
- [x] 后台插件 stage-configs.js 只支持对象，不支持数组，即一个插件只能生成一个父菜单。
- [x] 标签：已关注标签，不支持无限下拉功能

**Comment by luoyunchong** [comment]
vue3.0发布，在element ui发布 更新，跟进vue3.0的脚步。

**Comment by luoyunchong** [comment]
vue2、element-ui会有node-sass版本的引用，该包非常不易于安装，而且依赖python2编译，很离谱，所以后续升级vue3,element-plus包，删除node-sass，改用dart-sass，实际包为sass

**Comment by luoyunchong** [comment]
TODO

**Comment by luoyunchong** [comment]
vue3新版本：https://vvlog.igeekfan.cn/#/index

vue2版本移至：https://vvlog-vue2.igeekfan.cn/#/index

**Comment by luoyunchong** [comment]
# vue3存在的一些BUG

- 当登录状态不可用，自动退出，而不是一直提示 `请先登录 The token expired at '11/02/2022 17:00:48'`
